version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    image: notification_service_php
    container_name: notification_service_php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./web:/var/www:z
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:9000"
    networks:
      - alopeyk-brige


  mysql:
    hostname: alo_mysql
    image: mysql
    container_name: alo_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./Docker/data/mysql:/var/lib/mysql
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "50m"
    networks:
      - alopeyk-brige
#  db:
#    image: mysql-alo
#    container_name: mysql-alo
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: laravel
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_PASSWORD: root
#      MYSQL_USER: root
#    volumes:
#      - ./Docker/data/mysql:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    networks:
#      - alopeyk-brige



networks:
  alopeyk-brige:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: alopeyk-brige

